/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "onlyDao" | "onlyVillageHead" | "setDao" | "setVillageHead"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SetVillageHead"): EventFragment;

  encodeFunctionData(functionFragment: "onlyDao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onlyVillageHead",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setDao", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setVillageHead",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "onlyDao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onlyVillageHead",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVillageHead",
    data: BytesLike
  ): Result;
}

export namespace SetVillageHeadEvent {
  export type InputTuple = [headman: AddressLike, status: BigNumberish];
  export type OutputTuple = [headman: string, status: bigint];
  export interface OutputObject {
    headman: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IManager extends BaseContract {
  connect(runner?: ContractRunner | null): IManager;
  waitForDeployment(): Promise<this>;

  interface: IManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  onlyDao: TypedContractMethod<[], [void], "nonpayable">;

  onlyVillageHead: TypedContractMethod<
    [villageHead: AddressLike],
    [void],
    "nonpayable"
  >;

  setDao: TypedContractMethod<[_dao: AddressLike], [void], "nonpayable">;

  setVillageHead: TypedContractMethod<
    [villageHead: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "onlyDao"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onlyVillageHead"
  ): TypedContractMethod<[villageHead: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDao"
  ): TypedContractMethod<[_dao: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVillageHead"
  ): TypedContractMethod<
    [villageHead: AddressLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SetVillageHead"
  ): TypedContractEvent<
    SetVillageHeadEvent.InputTuple,
    SetVillageHeadEvent.OutputTuple,
    SetVillageHeadEvent.OutputObject
  >;

  filters: {
    "SetVillageHead(address,uint256)": TypedContractEvent<
      SetVillageHeadEvent.InputTuple,
      SetVillageHeadEvent.OutputTuple,
      SetVillageHeadEvent.OutputObject
    >;
    SetVillageHead: TypedContractEvent<
      SetVillageHeadEvent.InputTuple,
      SetVillageHeadEvent.OutputTuple,
      SetVillageHeadEvent.OutputObject
    >;
  };
}
