/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libs from "./libs";
export type { libs };
export type { IManager } from "./IManager";
export type { Manager } from "./Manager";
export type { POP } from "./POP";
export type { Permit } from "./Permit";
export type { Village } from "./Village";
