/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as libs from "./libs";
export { IManager__factory } from "./IManager__factory";
export { Manager__factory } from "./Manager__factory";
export { POP__factory } from "./POP__factory";
export { Permit__factory } from "./Permit__factory";
export { Village__factory } from "./Village__factory";
